### ISSUE TITLE
Expose DBClusterIdentifier

### ISSUE THREAD

**Issue by ambsw-technology** [cfn-modules/rds-aurora-serverless-postgres#11]
We deploy a DB per-client (as part of a complete dedicated stack) so the ability to name them simplifies administration considerably.  I have this working on an internal branch and can PR to this repo once these changes are merged (to avoid conflicts).

**Comment by michaelwittig** [comment]
sounds great. I will wait with the next release until this issue and #7 are closed?
PS: I fixed the Min&Max settings

**Comment by michaelwittig** [comment]
merged
