### ISSUE TITLE
DatabaseName is not required (DBName is)

### ISSUE THREAD

**Issue by ambsw-technology** [cfn-modules/rds-aurora-serverless-postgres#7]
I'm pretty sure I want all of my databases to be owned by specific pgSQL users.  I assume this database would be owned by the root user instead.  It's not clear (to me anyway) that this would be a best practice (to justify making it required).

**Comment by michaelwittig** [comment]
Just to get you right, your request is to make the DBName optional, right? I'm fine with that.

**Comment by ambsw-technology** [comment]
Yes thanks.  Will PR shortly.

**Comment by ambsw-technology** [comment]
I may be wrong on this.  I was under the impression that it was required from this line...

> DatabaseName: !If [HasDBSnapshotIdentifier, !Ref 'AWS::NoValue', !Ref DBName]

However `DBName` has the empty string as a default and that gets passed to the `DBCluster`.  I assume no table is created when the empty string is passed (instead of `AWS::NoValue`).
