### ISSUE TITLE
Custom ParemeterGroup in CFN Modules

### ISSUE THREAD

**Issue by ambsw-technology** [cfn-modules/rds-aurora-serverless-postgres#8]
Like [aws-cf-templates](https://github.com/widdix/aws-cf-templates/pull/428), I need to be able to provide a `DBParameterGroupName` so I can [require SSL connections](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Security.html#AuroraPostgreSQL.Security.SSL.Requiring).  Like that PR, I can submit a PR to multiple `cfn-modules` including postgres & mysql.  Interestingly `OptionGroup` is not available on the Aurora Cluster, but I can include it in the non-Aurora modules.

**Comment by michaelwittig** [comment]
Sounds great!

**Comment by michaelwittig** [comment]
merged
